SELECT TABLE_NAME
FROM (select table_name, ROWNUM AS RNUM from user_tables)
WHERE RNUM=12;

SELECT COLUMN_NAME
FROM (SELECT COLUMN_NAME, ROWNUM AS RNUM FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='BOOK')
WHERE RNUM=1;